version: "1.0"
services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio_user
      MINIO_SECRET_KEY: minio_password
    volumes:
      - minio-volume:/data

  postgres:
    image: postgres:14.9-alpine3.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_api
    networks:
     - locale-network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  minio-volume:
  db:
    driver: local
networks:
  locale-network:
    driver: bridge
